[package]
name = "scp-pack"
version = "0.1.0"
edition = "2021"

[dependencies]
zip = "2.1"
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0"
walkdir = "2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
